name: 'Sync Zenn articles to DEV'
description: 'Just sync Zenn articles to DEV.'
author: 'nikaera'
branding:
  icon: 'printer'  
  color: 'blue'
inputs:
  api_key:
    required: true
    description: 'The api_key required to use the DEV API (https://docs.forem.com/api/#section/Authentication)'
  username:
    required: false
    description: "Zenn user's account name. (Fields to be filled in if canonical url is set.)"
  title_format:
    required: false
    description: |
      Specify the DEV article title format. (ex. [{type}] {title} {emoji})
      {title} is required. {type} and {emoji} are not required.
    default: "[{type}] {title} {emoji}"
  articles:
    required: false
    description: "The directory where Zenn articles are stored."
    default: articles
  update_all:
    require: false
    description: "Whether to synchronize all articles."
    default: true
  added_modified_filepath:
    required: false
    description: |
      Synchronize only the articles in the file path divided by line breaks.
      You can use jitterbit/get-changed-files@v1 to get only the file paths of articles that have changed in the correct format.
      (https://github.com/jitterbit/get-changed-files)
outputs:
  articles:
    description: 'A list of URLs of dev.to articles that have been created or updated'
  newly-sync-articles:
    description: 'File path list of newly synchronized articles.'
runs:
  using: 'node20'
  main: 'dist/index.js'
